#suppress "experimental-feature" ""
import "./entities/repo.tsp";
import "./entities/branch.tsp";
import "./entities/pull_request.tsp";
import "./entities/pr_review.tsp";
import "./entities/pr_comment.tsp";
import "./entities/pr_status_check.tsp";
import "./entities/pr_label.tsp";
import "./entities/pr_requested_reviewer.tsp";
import "./entities/repo_event.tsp";
import "./entities/notification.tsp";
import "./entities/checkout.tsp";
import "./entities/call_log.tsp";
import "./entities/change_log.tsp";
import "./entities/poll_state.tsp";
